# Generated by Django 3.2.11 on 2022-06-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0002_auto_20220607_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsetting',
            name='SelectSectionForQuestion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testmake_testSectionQS', to='QuizData.testsection'),
        ),
    ]
