# Generated by Django 3.2.11 on 2022-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0003_alter_choice_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer_text',
            field=models.CharField(default=None, max_length=255, verbose_name='Answer Text'),
        ),
    ]
