# Generated by Django 3.2.11 on 2022-04-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0004_alter_choice_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='qid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ques_qdes3', to='QuizData.question'),
        ),
    ]
