# Generated by Django 3.2.11 on 2022-04-12 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_dlevel_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_auto_20220219_1449'),
        ('QuizData', '0005_alter_ques_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_answer3', to='QuizData.language'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='QuizData.ques'),
        ),
        migrations.AlterField(
            model_name='ques',
            name='ques_lang',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_qdes3', to='QuizData.language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlavel_question3', to='QuizData.dlevel'),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_question3', to='QuizData.language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qtype_question3', to='Quiz.qtype'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_question3', to='course.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(db_column='user', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ques_user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
