# Generated by Django 3.2.11 on 2022-04-13 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuizData', '0006_auto_20220412_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLayout',
            fields=[
                ('tl_id', models.AutoField(db_column='tl_id', primary_key=True, serialize=False)),
                ('tl_title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Testmake',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('te_id', models.AutoField(db_column='te_id', primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('noOfQuestions', models.PositiveIntegerField()),
                ('houre', models.PositiveIntegerField()),
                ('minute', models.PositiveIntegerField()),
                ('testCategoury', models.CharField(choices=[('Prectice', 'Prectice'), ('Examination', 'Examination')], default='1', max_length=20)),
                ('poolQuestion', models.BooleanField()),
                ('freeAvailable', models.BooleanField()),
                ('testShowFrom', models.DateTimeField()),
                ('testEndON', models.DateTimeField(blank=True, null=True)),
                ('testLayout', models.ForeignKey(db_column='test_layout', on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_TestLayout', to='QuizData.testlayout')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_user1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
