# Generated by Django 3.2.11 on 2022-04-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0007_testlayout_testmake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmake',
            old_name='houre',
            new_name='hour',
        ),
        migrations.RenameField(
            model_name='testmake',
            old_name='testCategoury',
            new_name='testCategory',
        ),
    ]
