# Generated by Django 3.2.11 on 2022-04-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0008_auto_20220413_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmake',
            name='totalMarks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testmake',
            name='testShowFrom',
            field=models.DateTimeField(verbose_name='%d/%m/%y %H:%M'),
        ),
    ]
