# Generated by Django 3.2.11 on 2022-04-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0009_auto_20220413_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmake',
            name='testCategory',
            field=models.CharField(choices=[('Practice', 'Practice'), ('Examination', 'Examination')], default='1', max_length=20),
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('ts_id', models.AutoField(db_column='te_id', primary_key=True, serialize=False)),
                ('sectionName', models.CharField(max_length=255)),
                ('hour', models.PositiveIntegerField()),
                ('minute', models.PositiveIntegerField()),
                ('allowedSectionSwitching', models.BooleanField()),
                ('skipSectionBeforeTimeOver', models.BooleanField()),
                ('studentChoice', models.BooleanField()),
                ('useSectionAsBreak', models.BooleanField()),
                ('showPreviousSection', models.BooleanField()),
                ('sectionInstruction', models.TextField(blank=True, default=None, null=True)),
                ('testmake', models.ForeignKey(db_column='testmake', on_delete=django.db.models.deletion.DO_NOTHING, related_name='testSeection_testMake', to='QuizData.testmake')),
            ],
        ),
    ]
