# Generated by Django 3.2.11 on 2022-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0010_auto_20220416_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsection',
            name='allowedSectionSwitching',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='hour',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='minute',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='showPreviousSection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='skipSectionBeforeTimeOver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='studentChoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='useSectionAsBreak',
            field=models.BooleanField(default=False),
        ),
    ]
