# Generated by Django 3.2.11 on 2022-04-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0011_auto_20220416_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmake',
            name='freeAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testmake',
            name='poolQuestion',
            field=models.BooleanField(default=False),
        ),
    ]
