# Generated by Django 3.2.11 on 2022-04-20 12:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizData', '0012_auto_20220416_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='question_para',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ques',
            name='question_text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ques',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='solution'),
        ),
    ]
