# Generated by Django 3.2.11 on 2022-05-31 09:01

from django.db import migrations, models
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('home_title', models.CharField(max_length=255, verbose_name='Title')),
                ('home_slug', models.SlugField(max_length=255, null=True, verbose_name='slug')),
                ('home_logo', models.ImageField(blank=True, default=None, null=True, upload_to=personal.models.upload_image_path_profile)),
            ],
        ),
    ]
