# Generated by Django 3.2.11 on 2022-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_text',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
