# Generated by Django 3.2.11 on 2022-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedemo', '0003_alter_image_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_text',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
    ]
