# Generated by Django 3.2.11 on 2022-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedemo', '0004_alter_image_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
