# Generated by Django 3.2.11 on 2022-04-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagedemo', '0005_image_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='text',
        ),
    ]
